#!/bin/bash
set -euo pipefail
cd $(dirname $0)/..

source ./auto/set-env

display_status "Step1: Clean source bucket"
aws s3 rm s3://${SOURCE_BUCKET_NAME} --recursive

display_status "Step2: Clean source bucket"
aws s3 rm s3://${TARGET_BUCKET_NAME} --recursive

display_status "Step3: Delete stack ${STACK_NAME}"
aws cloudformation delete-stack --stack-name ${STACK_NAME}