#!/bin/bash
set -euo pipefail
cd $(dirname $0)/..

PHASE=$1
source ./auto/env/${PHASE}

display_status "Step 1"
./auto/build ${PHASE}

display_status "Step 2"
./auto/package ${PHASE}

display_status "Step 3"
display_status "Deploy ${STACK_NAME} stack"

aws cloudformation deploy \
  --template-file ${AWS_CLOUFROMATION_TEMPLATE_URL}/${TRANFORMED_TEMPLATE} \
  --stack-name ${STACK_NAME} \
  --capabilities CAPABILITY_NAMED_IAM
