#!/bin/bash
set -euo pipefail
cd $(dirname $0)/..

source ./auto/set-env
DEPLOYMENT_STACK_NAME=yyl-deployment-stack

display_status "Deploy ${DEPLOYMENT_STACK_NAME} stack"

aws cloudformation deploy \
  --template-file ${AWS_CLOUFROMATION_TEMPLATE_URL}/deployment-bucket-creation-template.yml \
  --stack-name ${DEPLOYMENT_STACK_NAME} \
  --capabilities CAPABILITY_NAMED_IAM
