#!/bin/bash
set -euo pipefail
cd $(dirname $0)/..

source ./set-env

aws lambda invoke --function-name ${LAMBDA_NAME} --payload '{"key": "value"}' out
sed -i'' -e 's/"//g' out
sleep 15
aws logs get-log-events --log-group-name /aws/lambda/${LAMBDA_NAME} --log-stream-name $(cat out) --limit 100
