#!/bin/bash
set -euo pipefail
cd $(dirname $0)/..

Lambda_Name=yyl-lambda-function-001
aws lambda invoke --function-name ${Lambda_Name} --payload '{"key": "value"}' out
sed -i'' -e 's/"//g' out
sleep 15
aws logs get-log-events --log-group-name /aws/lambda/${Lambda_Name} --log-stream-name $(cat out) --limit 100