AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: For aws training - week 2 - Advanced phase
Parameters:
  LambdaFunctionName:
    Description: Lambda Function Name
    Default: yyl-week2-advanced-lambda-function-001
    Type: String
  LambdaPolicyName:
    Description: Policy Name
    Default: yyl-week2-advanced-lambda-policy-001
    Type: String
  LambdaLogGroupName:
    Description: Lambda LogGroup Name
    Default: yyl-week2-advanced-lambda-log-group-001
    Type: String
  LambdaRoleName:
    Description: Lambda Role Name
    Default: yyl-week2-advanced-lambda-role-001
    Type: String
  SNSTopicName:
    Description: SNS Topic Name
    Default: yyl-sns-topic-002
    Type: String

Resources:
  MyLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Ref LambdaLogGroupName
      RetentionInDays: 7

  MyLambda:
    Type: AWS::Serverless::Function
    DependsOn:
      - MyLambdaLogGroup
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Role: !GetAtt MyLambdaRole.Arn
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: ../../output/
      MemorySize: 128
      Timeout: 3     

  MyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref LambdaRoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: !Ref SNSTopicName
      TopicName: !Ref SNSTopicName

  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: TopicPolicy
        Statement:
          - Sid: allow-s3-to-publish-event
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - sns:Publish
            Resource: !Ref SNSTopic
          - Sid: allow-lambda-function-to-subscribe
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sns:Subscribe
              - sns:Receive
            Resource: !Ref SNSTopic
      Topics:
        - !Ref SNSTopic
  
  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt MyLambda.Arn
      Protocol: lambda
      TopicArn: !Ref SNSTopic

Outputs:
  MyLambda:
    Description: Lambda for practice
    Value: !Ref LambdaFunctionName
  SNSTopic:
    Description: SNS topic for lambda subscription
    Value: !Ref SNSTopicName